import { google } from 'googleapis';

/**
 * Updates values in a Spreadsheet.
 * @param {obj} client The client generated by google authorization
 * @param {string} spreadsheetId The spreadsheet ID.
 * @param {string} range The range of values to update.
 * @param {object} valueInputOption Value update options.
 * @param {(string[])[]} values A 2d array of values to update.
 * @return {obj} spreadsheet information
 */
export default async function updateSpreadsheetValuesProvider({
  client,
  spreadsheetId,
  range,
  valueInputOption,
  values,
}) {
  const googleSheetsService = google.sheets({ version: 'v4', auth: client });

  const resource = { values };

  const response = await googleSheetsService.spreadsheets.values.update({
    spreadsheetId,
    range,
    valueInputOption,
    resource,
  });

  return response;
}
